### ISSUE TITLE
Consider using UTF-8 as default charset on databases created during import.

### ISSUE THREAD

**Issue by ThomasKristensen** [keeps/db-preservation-toolkit#132]
Are there any known downsides to making UTF-8 the default encoding/charset on created databases?

Seen from the siard-dk side of things (still being relatively new on the project, though) setting the default encoding at the database level seems to make a lot of sense. Setting the default charset on the created database, ensures that any columns of type VARCHAR (and similar) will be of encoding UTF-8. As we don't have encoding information in the database type declaration in the column definitions in the archive file - and as allow their cell/data values to be encoded in UTF-8 - the only way to guarantee, that a varchar value originally of unknown encoding, but now encoded in UTF-8 in the xml-file, can be imported in a varchar column in the target database, is to make that varchar column of encoding UTF-8. This is the way the situation looks to me from the siard-dk side of things, at least. But don't you guys face the same problem in siard-1(/2)?

As for implementing it, I guess it should be relatively straightforward, making a DB-specific implementation of createDatabaseSQL() in the DB-specific SQL-helpers, if I have understood things correctly.

E.g. for PostgreSQL the postfix to the create table statement would be `"WITH ENCODING = 'UTF8'"`.

**Comment by luis100** [comment]
IMHO, because we connect to the source database using JDBC and fetch the raw data using the DBMS driver specific methods, we can assume that the encoding of fetched information is UTF-8 (because Java internally uses UTF-8 for Strings). Nevertheless, some UTF-8 control characters that are illegal in XML would be escaped using the rules defined in SIARD 2 specification.

When we do the reverse process, and convert SIARD back to a DBMS, we will be again using the DBMS driver which will convert the text encoded in SIARD in UTF-8 to the DBMS specific encoding, whatever it might be. There can be reasons for a user to select a specific encoding for it DBMS, specially if said DBMS does not support UTF-8. So I guess that the encoding selection should be up to the user. 

So in my opinion we should meddle with this things unless we need to. Can you point any reason why we need to?

**Comment by ThomasKristensen** [comment]
Thanks for your response. 

I believe that you are right in most of what you are saying. 

However, you write that:

> the DBMS driver which will convert the text encoded in SIARD in UTF-8 to the DBMS specific encoding, whatever it might be.

The way I see it, this can only be true, provided that the DBMS specific encoding can in fact encode all the values. Say the varchar column has inherited the default encoding of the database, which might very well be ISO-8859-1. I don't see how the JDBC driver can convert all possible unicode characters to ISO-8859-1. Am I missing something?

And you might perhaps argue that the since the original datatype of the exported column was varchar (and not nvarchar) the data will not use the full spectrum of unicode characters, which is correct - however since we don't know the encoding of the original varchar column, we cannot know, which small subset of the unicode characters the varchar data does contain.

I therefore maintain - in the absence of information regarding default encoding of the database exported to the archive and in the absence of information of the db-server default encoding for new databases - the only way to  ensure that we can in fact import the varchar data encoded in utf-8 in the xml-archive - is to make the default encoding of the created database some unicode format, e.g. UTF-8.

Or am I missing something?

**Comment by luis100** [comment]
As you can see, for example, in [Java NIO Chartset#encode()](http://docs.oracle.com/javase/6/docs/api/java/nio/charset/Charset.html#encode(java.nio.CharBuffer)):

> This method always replaces malformed-input and unmappable-character sequences with this charset's default replacement string.

This has already happened when converting the database from the original DBMS into UTF-8 and would happen again if converting from UTF-8 on the archive to, for example, ISO-8859-1. So this would be an argument for selecting UTF-8 as the default encoding for exporting to a DBMS.

On the other hand, export to a DBMS serves for a user to be able to re-use the database for his own purposes. He selected the DBMS encoding when installing it (or could have selected).

For me either way is fine, I guess that we would need to have some user feedback to assure this is in fact what they would expect to happen.

**Comment by ThomasKristensen** [comment]
Thanks for bringing the default replacement string in the case of unmapped characters to my attention. That is certainly a relevant part of the picture.

I doesn't change the matter, though. 

Also notice that the default encoding of the exported varchar columns may even be unicode themselves. (For an MySQL example see http://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html )

The only way to ensure, that the data in unicode varchar columns can be imported without loss of data ( in the form of characters converted to the default replacement string ) in varchar columns in the target database, is to make the encoding of these unicode.

I think, I'll rest my case here. I think, that I have managed to bring the issue to your attention. I'll talk to my customer/employer, to determine if they want a solution, that is able to handle such scenarios gracefully for siard-dk - or they think it should be up to the user to configure the db-server used for the import, to make sure no data is lost in these special cases - or they don't care if either way is chosen. 

Thanks.

**Comment by regrat** [comment]
This is the archival point of view: we need a long term format and minimal diversity. Thus an argument of "possible reuse in production" is not the primary concern. Having all databases in the same codeset (i.e. UTF-8, which seems most appropriate for Europe) is a step in this direction. Otherwise we just postpone this step to the creation of DIP - and we are stil in the scope of E-ARK. When you ingest a database, you should know its codeset. Thus you could enter it as a parameter to the SIARD tool which could do the character set conversion into UTF-8 for all text fields. There is a risk for some unwanted change but I would leave this part to the responsiblity of the person who examines the database structure before the ingest. Also note that the archives ingest old databases so a whole range of codesets could appear inthe SIP without the conversion.

Regards, Boris

**Comment by chalkos** [comment]
To wrap up this issue, a few (beta) releases ago I forced the default charset/encoding used in dbptk to be UTF-8 (worst case scenario by forcing the user to use a specific extra parameter). The definitions for charset/encoding vary and even overlap depending on the source, making this discussion harder :)

By forcing UTF-8 globally, dbptk ensures that all textual content will be read and written in utf-8 (even in internal code that is not controlled by this project developers). Java always uses UTF-16 internally to be able to handle all (or at least most of) the characters, but since UTF-16 is a superset of UTF-8 this does not affect the conversion.

To conclude, I am considering this fixed and closing the issue. Feel free to continue commenting and discussing this topic.
