### ISSUE TITLE
Default schema override

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#178]
I am refering to #161 and #164 as it is not clear to me what is a solution for such a scenario where schema is not captured. The use case could be the following:  I create one target database (e.g. registerXY) and then restore two versions from SIARD-2 as two schemas (e.g. period12 and period34 from two AIPs). Then I can use both versions and compare the data. 
Source is MS Access: The schema public seems to be a default but I would like to override it.
Source is PostgreSQL: The original schema name should be preserved. But if it is "public" I would be happy with the possibility to change it, but this is not a priority.  

Steps required to reproduce the bug:

1. MS Access -> SIARD-2
2. SIARD-2 --> PostgreSQL
3.  the tables are created in the default (public) schema

**Comment by chalkos** [comment]
In #164 there is this paragraph:

> Feature: Allow overriding the target schema in these cases so that **many single-schema databases** can be converted **into a single multi-schema database** (each saved in its own schema, avoiding any conflicts).

Is this the kind of solution you were referring to? (overriding the target schema)

**Comment by BorisDomajnko** [comment]
Yes. Currently I am working on MS Access borm data and I miss the target schema functionality. This all is connected also with the DB viewer, I understand you will do it.
(BTW, I cannot test with my second MS Access database from the same creator as it cannot be restored until the wrong year " 207" issue #171 is fixed, too many errors in original db for manual corrections).

**Comment by chalkos** [comment]
I am aware that you need the functionality described in #164, I am currently planning on improving the stability of future releases. The next features to implement and issues to fix are listed in the next milestone https://github.com/keeps/db-preservation-toolkit/milestones (currently https://github.com/keeps/db-preservation-toolkit/milestones/v2.0.0-beta4.2).

As you can see #171 is listed for the next milestone, #164 is scheduled for a later release (not necessarily 2.0.0-final, as it can be moved up the timeline).

Since the functionality requested in this issue is described in #164, I am marking this issue as a duplicate and closing it. Feel free to comment if you believe this is not a duplicate issue.
