### ISSUE TITLE
siard2 to postgresql ERROR 

### ISSUE THREAD

**Issue by dglab-arquivos** [keeps/db-preservation-toolkit#204]
Description: when exporting a siard2 to postgresql a message error appears and some data isn't migrated.

Aditional notes: in a table export of 399103 lines only 399049 appear amd in a table of 11 rows 0 apeears  (with select count)
the sabe database was exported to mysql and all the data is exported and no errors appear.
[dbptk-app.log.txt.zip](https://github.com/keeps/db-preservation-toolkit/files/279762/dbptk-app.log.txt.zip)

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment]
This is a bug in PostgreSQL export module. Thanks for reporting it.

Personal notes:
`handleDataCloseTable` in postgresql export module is using the import table id and not the export table id, so it fails because schema `dbo` does not exist. this throws and exception and does not proceed to close the table, everything is left in an unstable state and some of the data is not inserted/committed.
