### ISSUE TITLE
SIARD2.0 Export fails for LOBs outside the SIARD folder structure

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#234]
I have a pilot database that successfully exports to SIARD2.0 where CLOBs and BLOBs are stored as files inside the SIARD table folder structure. 

When I try to export to a folder outside the SIARD folder structure, i.e. outside of the SIARD archive file, the export process stops after 55.000 LOBs have been successfully created.  See error message:
[externallobs.txt](https://github.com/keeps/db-preservation-toolkit/files/393160/externallobs.txt)

I have looked at the table in the database. It seems that there are a lot of small CLOBs in it. When exporting where CLOBs and BLOBs are stored as files inside the SIARD table folder structure only very few CLOBs are exported to external files, (most data remains as inline text in the table data). But when exporting to a folder outside til SIARD folder structure, all CLOBs are exported no matter their size (?). If this is right I guess the process stops when handling a certain CLOB, that DBPTK did not handle in the first export.

**Comment by PhillipTommerholt** [comment]
Update:
I have isolated the table by the list-tables-module and so far it has exported 150.000 files from the table.. so it might just be an i/o mistake not related to the DBTPK. 

I will try to make a full export again if the export of the table succeeds.

**Comment by chalkos** [comment]
(as you probably already know) There are 3 ways to store LOBs:
1. inlined inside the XML,
2. as a file inside the zip,
3. as a file outside the zip.

> I have looked at the table in the database. It seems that there are a lot of small CLOBs in it. When exporting where CLOBs and BLOBs are stored as files inside the SIARD table folder structure only very few CLOBs are exported to external files, (most data remains as inline text in the table data). 

This is because DBPTK is using method 1 for small LOBs and 2 for bigger ones. Although this seems to work great and seems like kind-of intelligent behaviour, the SIARD spec (or the LOB recommendation) recommends that only one method is used, i.e. either do 1 or 2.

> But when exporting to a folder outside til SIARD folder structure, all CLOBs are exported no matter their size (?)

This follows the recommendations and uses method 3 for all LOBs.

About the error, it is probably dbptk related.
55.000 files seems like an unlikely number for a random IO error, unless it is some filesystem limit, but unless you are using an ancient filesystem, this shouldn't be the problem.

a quick google search revealed [1](http://stackoverflow.com/questions/27335005/java-nio-files-createfile-fails-with-nosuchfileexception), [2](http://stackoverflow.com/questions/14263725/java-files-write-nosuchfileexception), [3](http://stackoverflow.com/questions/30735735/nosuchfileexception-when-creating-a-file-using-nio) examples similar problems and all of them are related to trying to create files without creating the parent folders first.

So this is probably DBPTK not creating parent directories when creating the file.

Let me know how the export of the table goes.

PS: I will need to know the -eelpf (`--export-external-lobs-per-folder`) and -eelsf (`--export-external-lobs-folder-size`) parameters you used (or if you used the default values) when exporting the SIARD, in case this is a bug.

**Comment by PhillipTommerholt** [comment]
I got the same search result and that is why created this issue.
However, it seems that there is a volatile connection to the disk that I use as destination folder (and temp folder).

I am running a new export with another disk. The problematic table has been exported successfully (500.000 CLOBs) and is on its way to export the rest of the tables. 

I changed the parameter. In the first run I set the limit to 8.000 per folder (<10.000), but since there are many small CLOBs I have raised the limit to 18.000 per folder (>10.000). When I hopefully get a successful export I will try to do another export with 8000, just to check.
