### ISSUE TITLE
Maven build error: cannot access http://artifactory.keep.pt/keep

### ISSUE THREAD

**Issue by andreaskring** [keeps/db-preservation-toolkit#235]
Description: cannot build latest version of the master branch with Maven. 

Steps required to reproduce the bug:

1. Fetch the latest version of the master branch with git and switch to this branch.
2. Run `mvn clean package`

Maven complains about not having access to artifactory.keep.pt... (see attached log file
[mvn.txt](https://github.com/keeps/db-preservation-toolkit/files/393596/mvn.txt))

**Comment by chalkos** [comment]
I've been using local dependencies. I'll fix that in a moment.

**Comment by chalkos** [comment]
It turns out that I have not been using local dependencies after all. Are you able to access [this file](http://artifactory.keep.pt/keep/com/databasepreservation/visualization/dbvtk-model/1.0.0-SNAPSHOT/maven-metadata.xml) from your browser?

This seems like a network problem. And it works for me, even when accessing from outside KEEPS... can try again or check if there is some firewall blocking your access?

**Comment by andreaskring** [comment]
Yes - I can access the file you link to.

**Comment by chalkos** [comment]
Ok, so it's not a network problem.

Maven was complaining that it could not access it (permission denied). Try maven again. If it can not access it may be a maven problem.

**Comment by andreaskring** [comment]
Ok - I have just tried `mvn clean package` again and now it is working. I am getting some warnings though (see below - should I worry about these), but the build is successful. Thanks for the help.

Downloading: file://${project.basedir}/../vendor-libs/repository/com/databasepreservation/visualization/dbvtk/1.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.databasepreservation.visualization:dbvtk:1.0.0-SNAPSHOT/maven-metadata.xml from/to vendorDependencies (file://${project.basedir}/../vendor-libs/repository/): Repository path /../vendor-libs/repository does not exist, and cannot be created.
[INFO] Building jar: /home/andreas/eark/db-preservation-toolkit/dbptk-core/target/dbptk-app-2.0.0-SNAPSHOT.jar
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /home/andreas/eark/db-preservation-toolkit/dbptk-core/target/dbptk-app-2.0.0-SNAPSHOT.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/andreas/eark/db-preservation-toolkit/dbptk-core/target/dbptk-core-2.0.0-SNAPSHOT.jar
with assembly file: /home/andreas/eark/db-preservation-toolkit/dbptk-core/target/dbptk-app-2.0.0-SNAPSHOT.jar

**Comment by chalkos** [comment]
Maybe it has something to do with it being a snapshot, so it is trying to get it from the local repository and failing (because it is not there but in keep's artifactory). But it does obtain it from keep's artifactory because otherwise it would not compile.

That said, you can ignore those warnings.
