### ISSUE TITLE
backward compability not supported

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#257]
Description: At the moment when new version of dbptk comes out then we can not use old SIARD files generated with older versions.

**Comment by chalkos** [comment]
DBPTK is being developed and tested, and does not ensure, at this phase, that the generated SIARD files are 100% correct, complete and valid (otherwise it would be finished :smile: ).

The tool should always be compatible with correct and complete SIARD packages. As an example, if DBPTK was generating an invalid SIARD packages 2 versions ago, it should not even be able to read those, because they are **not** SIARD.

/cc @luis100 @jmaferreira

**Comment by chalkos** [comment]
So the tool will be compatible with old SIARD files, generated by older versions, as long as those were valid SIARD files.
