### ISSUE TITLE
Cannot export SIARD-file to MS SQL Server due to naming of MySQL primary keys

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#262]
In pilot 1 I visited a producer site and successfully exported a database on a MySQL server to a SIARD2-file.

I now want to export the SIARD-file to a MS SQL Server. This fails and it is probably due to the fact that the primary keys are not uniquely named. They are all named `PRIMARY` in metadata.xml. This is related to #183 but it is the other way around. 

See these links for naming primary keys: 
http://stackoverflow.com/questions/3303798/mysql-name-primary-key-in-create-table-statement 
http://dev.mysql.com/doc/refman/5.7/en/create-table.html

I will make a work-around and just alter the names in the metadata.xml, but since this a general problem: should DBPTK change the naming of non-unique MySQL primary keys in the export process in order to export to other database servers? For example naming them something like this:

```
DBPTKgeneratedPKname_1
DBPTKgeneratedPKname_2
DBPTKgeneratedPKname_3
```

in the end product (keeping the original siard-file intact)?

**Comment by chalkos** [comment]
I will have to check the SQL specification to base my choice on the spec:

* if the specification says that primary key names must be unique then all import modules should ensure that (in this case MySQL is deviating from the standard)
* otherwise, MS SQL Server is being picky (and deviating from the standard) and its export module should ensure that there are no primary key name conflicts

**Comment by chalkos** [comment]
This is fixed in beta7.1 (lost track of the exact commit, sorry). I changed MySQL import module to attempt to use unique key names.
