### ISSUE TITLE
Missing primary key constraint names in MSSQLServer

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#28]
When round-trip testing from MSSQLServer to SIARD and back, the name of the primary key constraints is lost. Example: `CONSTRAINT [PK_Bibliography_1] PRIMARY KEY CLUSTERED > PRIMARY KEY CLUSTERED`.

**Comment by Laurira** [comment]
I think this issue is not completely fixed
I reproduced this using dbptk-app-2.0.0-beta4.0.jar

1. I did an export from Postgre to SIARD-2
[metadataPostgre.xml.txt](https://github.com/keeps/db-preservation-toolkit/files/227633/metadataPostgre.xml.txt)

2. I imported this file to MySQL
3. and then I exported MySQL to SIARD-2
[metadataMySQL.xml.txt](https://github.com/keeps/db-preservation-toolkit/files/227641/metadataMySQL.xml.txt)

4. I compared the files metadataPostgre.xml and metadataMySQL.xml

For example in line 173 Postgre has <name>pk_admin_unit</name> but MySQL has <name>PRIMARY</name>

**Comment by chalkos** [comment]
@Laurira this issue is about a roundtrip test for MSSQL Server, which means convert MSSQL to SIARD, then convert the SIARD back to MSSQL and then compare the original MSSQL db and the restored MSSQL db to see what changed.

Your issue seems to be a different one. I duplicated your comment in #183.
