### ISSUE TITLE
Beta6 does not create messageDigests in tableX.xml for BLOBs

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#295]
I used Beta6 and exported a database containing LOBS (LOBS inside the SIARD package folder structure.)

SIARD2.0 format specification T_6.4-5 states that there must be three attributes:
file
length
digest

DBPTKBeta6 only creates file and length, not digest.
(There is a small mistake in the specification since the example also only shows file and length, but the text in the specification states that all three must be present)

**Comment by chalkos** [comment]
In the example for Table0.xsd (page 75):

<img width="516" alt="screenshot of google chrome" src="https://cloud.githubusercontent.com/assets/98429/22420963/e15daa4c-e6dc-11e6-9d09-d43fadd31906.png">

The `messageDigest` attribute is optional, because it does not have `use="required"`.

This leads me to think that someone might have made a mistake in including the digest in the "must" part. Because that is the only place in the specification where the digest is mandatory.

**Comment by PhillipTommerholt** [comment]
> The  messageDigest  attribute is optional, because it does not have  use="required" . This leads me to think that someone might have made a mistake in including the digest in the "must" part. Because that is the only place in the specification where the digest is mandatory.

Yes, I think so too. I cc'ed you in an email to Marcel Monday 23rd of January 10:52. I am in contact with him and he will investigate and discuss if it is: 
- a small mistake in the text in T_6.4-5 
- or a mistake in the example and the schema ind the appendix. 

So we are waiting for his response.

**Comment by luis100** [comment]
@PhillipTommerholt was there a response for this issue?

**Comment by chalkos** [comment]
From the emails, it looks like this was discussed (although I believe I was not CC'ed in all the emails) and an appropriate solution was implemented in the SIARD 2.1 specification.

**Comment by PhillipTommerholt** [comment]
I never got an answer back on this. Last year I created this issue summing up the problems in the specification:
https://github.com/DILCISBoard/SIARD/issues/3

So I guess it lives on in another thread and this can indeed be closed.
