### ISSUE TITLE
Error converting SQL Server timestamp field

### ISSUE THREAD

**Issue by ClausMunch** [keeps/db-preservation-toolkit#322]
Description: 
Version: dbptk-app-2.0.0
Trying to export timestamp column, results in a fatal error. The timestamp datatype in SQL Server is actually a rowversioning and thus fails.

From the dbptk-app log:
```
2017-09-12 08:53:16,606 [main] ERROR (c.d.Main) Fatal error while converting the database (Unable to export column [Timestamp] in table [Booking], as siard-dk doesn't support the normalized SQL data type of the column: [BINARY] )
com.databasepreservation.model.exception.ModuleException: Unable to export column [Timestamp] in table [Booking], as siard-dk doesn't support the normalized SQL data type of the column: [BINARY] 
	at com.databasepreservation.modules.siard.out.content.SIARDDKContentExportStrategy.openTable(SIARDDKContentExportStrategy.java:189)
	at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.handleDataOpenTable(SIARDExportDefault.java:163)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1617)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)
```

**Comment by chalkos** [comment]
Can you provide me more info on the column `Timestamp`? It should be in the first part of the log, where metadata is obtained. I need it to understand which column type did the application perceive.

It should look something like this (although the values may be different)

```
2017-09-13 10:25:17,982 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Data type: 12
Type name: VARCHAR
Column size: 45
Decimal digits: 0
Radix: 10
Remarks: The actor's last name.
Default value: null
Index: 3
Is Nullable: false
Is auto increment: false
Calculated type: SimpleTypeString
ColumnType hash: -933492926
```

**Comment by ClausMunch** [comment]
`2017-09-12 08:44:19,308 [main] DEBUG (c.d.m.Reporter) dataTypeChangedOnImport, invoker: com.databasepreservation.modules.sqlServer.in.SQLServerDatatypeImporter; message: - Type conversion in import module: in `dbo.Booking.Timestamp` (format: schema.table.column) has original type `TIMESTAMP(8)` and was converted to the standard type `BINARY`; and type: Type{description='null', originalTypeName='timestamp(8)', sql99TypeName='BINARY', sql2008TypeName='BINARY'}-->SimpleTypeBinary{formatRegistryName='null', formatRegistryKey='null', length=8}`

```
2017-09-12 08:44:19,308 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Data type: -2
Type name: timestamp
Column size: 8
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 12
Is Nullable: false
Is auto increment: false
Calculated type: SimpleTypeBinary
ColumnType hash: -2019556790
```

**Comment by chalkos** [comment]
I know that the SIARD-DK module is supposed to handle binary types (I did not write that one myself) but it seems it is also filtering out any SQL Standard Types that it doesn't understand (in a very strict way, since it is excluding a binary type even though it can handle binary types).

A fix for the SIARD-DK module might be handling the type `BINARY` the same way `BINARY VARYING` (or whatever binary type is currently supported) is handled. But I'm not familiar enough with SIARD-DK's way of handling binary types to say for sure.

@PhillipTommerholt do you know if SIARD-DK stores fixed-length binaries and variable-length binaries in the same way?

**Comment by PhillipTommerholt** [comment]
Yes, this is related to https://github.com/keeps/db-preservation-toolkit/issues/290 

The SIARDDK-standard accepts fewer data types than SIARD2.0:
![datatypes](https://user-images.githubusercontent.com/15984159/30685572-a28afd38-9eb5-11e7-8fd1-d54da217eaa6.png)
So there are situations where the DBPTK SIARDDK module meets "unknown" data types  and handle these as errors and the export stops since there is no obvious link to convert this data type to an accepted data type. This is of course a bug as mentioned in issue 290. I see no problem if DBPTK handles fixed-length binaries and variable-length binaries in the same way.

**Comment by chalkos** [comment]
I came across another database with a `timestamp` columns and since #290 already covers the part about SIARD-DK's fault, I'll make this issue about the SQL Server problem.

Seems like `timestamp` and `rowversion` are correctly identified by the SQL JDBC driver as binary types, but then the driver can not fetch those values as binary data but it can get them as text.

A commit is on the way with a fix for this.

@jmaferreira this is the timestamp problem we talked about.
