### ISSUE TITLE
Materialised views (as tables)

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#348]
Most of the institutions' databases have important views and also views represent logic (queries) and better understanding of the information system.

Extracting views metadata is supported by all common DBMS, but there may be some issues on specific ones and other DBMS not currently supported that may need specific development.

Issues or support for specific DBMS that do not follow JDBC convention must be budget independently.
 
Views will be materialized as tables as the SIARD format does not support the concept of views. Such tables will be identified via a prefix on the table name.

**Comment by Laurira** [comment]
As now the views are treated more like tables then we have an issue (dbptk will freeze) to create the table list for big databases that contain views that are not optimized for counting the rows (but dbptk tries to add the number of rows for each table/view).
When user gets the table list with some other software (ie DBeaver) and then provides only the table names and excludes the views so that dbptk will not freeze any more we will miss some of the data, because the queries (SELECT .... FROM ...) of the views are still important to migrate.

So for now this issue has made the dbptk worse than it was before... There should be done two fixes:
1. Remove the counting queries (select count from ...) from the views.
2. By default all the views will not be materialized. User can add list of views that should be materialized.
