### ISSUE TITLE
Questions regarding exporting LOBs

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#372]
@chalkos in https://github.com/keeps/db-preservation-toolkit/issues/343#issuecomment-483244696
 > @PhillipTommerholt by default, DBPTK stores small lobs in the XML, bigger lobs are stored in their own file (inside the specified folder). The folder is specified in the metadata because if a lob is saved in a file, that's where it will be. In this case all the LOBs were small, so they were all inlined in XML.
> 
I have a few questions regarding exporting LOBs.

What is the definition of small/bigger lobs? I can't seem to find any information on this in the [documentation](https://github.com/keeps/db-preservation-toolkit/wiki). Is there a way for the user to define this limit? Or is there a way to state that all LOBS should be exported as files inside til SIARD file no matter the size?

I understand that the -eel parameter in SIARD-2 export module takes all the LOBs and export them to a external folder outside the SIARD files and does not distinguish between small or bigger.

**Comment by chalkos** [comment]
The specification allows 3 kinds of LOB handling:

_a)_ write them in the table.xml
_b)_ save them as a file inside the SIARD zip
_c)_ save them as files outside the SIARD zip

After a discussion (during the E-ARK project) on whether DBPTK should use *(a)* or *(b)*, we decided that it should use *(a)* for small LOBs and *(b)* for bigger LOBs. *(c)* is a different option which puts all LOBs in files outside the SIARD zip.

> What is the definition of small/bigger lobs?

At the moment DBPTK chooses automatically which of *(a)* or *(b)* to use:

* If it is a Character LOB bigger than 4000 bytes, use *(b)*;
* If it is a Binary LOB bigger than 2000 bytes, use *(b)*;
* Otherwise use *(a)*.

> Is there a way for the user to define this limit?

No.

> Or is there a way to state that all LOBS should be exported as files inside til SIARD file no matter the size?

Also no.

> I understand that the -eel parameter in SIARD-2 export module takes all the LOBs and export them to a external folder outside the SIARD files and does not distinguish between small or bigger.

Correct. That corresponds to method *(c)*

**Comment by PhillipTommerholt** [comment]
Thank you for your answers, Bruno.
