### ISSUE TITLE
if SDO_POINT_TYPE in Oracles SDO_Geometry has null values, then geodata is not exported

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#374]
Description: 

Steps required to reproduce the bug:

1. Take a dump which I will send to Luis directly (geodata problem.zip)
2. Upload it to your database
3. run dbptk against it

Header says lob6 is created for geodata but in the content there are no such folder.

**Comment by tomasmferreira** [comment]
In this case the geodata is being correctly exported into the respective table's xml file.

As you know, there is a threshold up to which lobs are written in the table XML for efficiency. This threshold is currently hardcoded and not configurable.
Since every geometry here represents only a single point their gml form is considered a *small clob*, therefore there is no need to store them outside the xml. If any of them would be large enough to be considered a *big clob* then they would go into that `lob6` folder. 

The indication by the header serves to state where these lobs are if they are not found in the xml file relative to the table.
