### ISSUE TITLE
Files as external LOBs are skipped because of filepath

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#398]
In the table, the reference to the file can be "folder/file.txt" or "folder\file.txt, depending on the operating system. The business application will deal with it. But if we make roundtrip of databases with DBPTK, then we loose some of the files:

```
2019-09-16 14:28:30,674 [main] DEBUG (c.d.m.Reporter) something was ignored, message: - Information: `Cell models.picture.4` was ignored because /home/doma/dbdipview/www/files/TestAndDemo1/pictures\24_Stick_15.jpg could not be found
```

I suggest that DBPTK behaves platform agnostic regarding the use of / or \ in the filepath in the table column.

Same test case as #397

**Comment by hmiguim** [comment]
Hi Boris,

could you please tell me what is the base path that you used and what was the value in the database?

**Comment by BorisDomajnko** [comment]
Miguel,
here: 
--filter1-base-path=/home/doma/dbdipview/www/files/TestAndDemo1
```
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (239, NULL, NULL);
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (237, 'first', NULL);
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (238, 'second', NULL);
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (235, 'The Stick model', 'pictures\24_Stick_15.jpg');
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (236, 'The Pitts model', 'pictures/14_Pitts_20.jpg');
INSERT INTO "AirplanesLinks".models (id, name, picture) VALUES (234, 'What time is it?', '07BeeGee_20.jpg');
```
And the folder:
```
TestAndDemo1/07BeeGee_20.jpg
TestAndDemo1/pictures/14_Pitts_20.jpg
TestAndDemo1/pictures/24_Stick_15.jpg
```

**Comment by hmiguim** [comment]
The operating system independence cannot be done, the tool have to infer if the \ character belongs to the file name or if is part of the path. The database cell value must be explicit to where the file is. We could replace all the separator characters by the system ones, but if the \ character belongs to the file name? That file will me missing. It is not that straight forward. 

At this moment DBPTK as is doesn't support cross platform paths. All the paths in the database must be in conformity with the used operating system. If Windows use POSIX representation, if Linux or MacOS use UNIX representation.

It is the normal output to ignore the file since it was not found in the file system.

**Comment by BorisDomajnko** [comment]
Hello Miguel,
this is a test case and I do not know how applicable it will be in real life. But it can happen that you get a database from Windows (e.g. MDB) and you run DBPTK on linux. In this case an archive is not allowed to loose any data. This means:  the export to SIARD needs to be done on the same operating system. And we do not want to change the characters in the column (\<->/)
When SIARD is unpacked (anywhere), the files will be there again and dealing with / and \ is a problem of renderer.

**Comment by hmiguim** [comment]
Hello Boris,

I understand the issue, but as I mentioned above, at this moment DBPTK as is doesn't support cross platform paths. We may consider in future iterations to approach this as a feature request.
