### ISSUE TITLE
2.3 or higher db-preservation-toolkit

### ISSUE THREAD

**Issue by whsmith100** [keeps/db-preservation-toolkit#401]
Is Version 2.1 db-visualization-toolkit compatible with preservation tool kit 2.3 or higher Description: 

Steps required to reproduce the bug:

1. 
2. 
3. 

Attach the dbptk-app.log.txt file below.

**Comment by luis100** [comment]
The validator currently only support SIARD 2.1. Also, there are some small issues with SIARD files created with previous versions of the tool that were fixed in new versions.

To upgrade the SIARD file, from 2.0 to 2.1, or to fix the problems with SIARD 2.1 files, you just need to upgrade SIARD. You can do this upgrade using the CLI or the Desktop app.

Using the [CLI](https://github.com/keeps/db-preservation-toolkit/releases/latest):
`java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.6.1.jar migrate -i siard-2 -if 2.1.siard -e siard-2 -ef 2.1-FIXED.siard`

Using the [Desktop](https://github.com/keeps/db-visualization-toolkit/releases/latest):
Open the SIARD, and select "Migrate to SIARD", follow the wizard.
![Captura de ecrã de 2019-10-14 13-16-04](https://user-images.githubusercontent.com/631728/66752388-30502600-ee89-11e9-9060-8c13cf3bd496.png)
