### ISSUE TITLE
dbptk import-export module  - using password (-ip -ep) on command line

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#408]
When user tries to import/export from/to some database and provides password that contains for example symbol < then user gets authentication error. Although user password really is ajsldkfjasldk>adfjk that user can use to connect to mysql environment for example.
When user did change the password so that it did not contained symbol > then the same command worked.

it is quite annoying issue (took 30 minutes to understand what I did wrong), there could be more symbols that dbpkt forbids from the passwords. I assume GUI works differently but just in case you could check this also

**Comment by hmiguim** [comment]
Using the command line interface some symbols are interpreted differently from others by the terminal. In that case (assuming that is an UNIX system) the symbol < or > are redirection operators. In order to use that symbol as a plain character you need to wrap it around single or double quotes.

In the GUI the problem itself will disappear since there is no terminal system behind trying to interpret the symbols.
