### ISSUE TITLE
validator results - uniqueness of trigger name per table

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#429]
Maybe this is a siard creation error not validator error but either way something seems to be wrong here.

A_M_5.13-1-1: [ERROR] : Trigger name REFACTION must be unique per table (metadata.xml schema:mnt/table:OMADUS/trigger:237)
A_M_5.13-1-1: [ERROR] : Trigger name REFACTION must be unique per table (metadata.xml schema:mnt/table:OMADUS/trigger:238)

metadata.xml:
![image](https://user-images.githubusercontent.com/3479156/73169648-35b64100-4105-11ea-932a-698fe37b8605.png)

database (I do not have trigger named REFACTION):
![image](https://user-images.githubusercontent.com/3479156/73169666-3fd83f80-4105-11ea-8fd3-aedbb3f86328.png)

**Comment by hmiguim** [comment]
Sybase is creating a set of triggers for each action that involves a foreign key update. Those triggers are automatically generated by Sybase with the name REFACTION. To solve this problem, those triggers are ignored since they can be recreated by create the table with the metadata available on the SIARD.


Closed at edf111f.
