### ISSUE TITLE
Filter options do not work correctly

### ISSUE THREAD

**Issue by ErikOlesen46** [keeps/db-preservation-toolkit#448]
Description: 
Hi,
I can not get the filter options to work for the filter 'external-lobs'!

Steps required to reproduce the bug:

This command works:
	java -jar "-Dfile.encoding=UTF-8" ../Programmer/dbptk-app-2.8.0.jar migrate -i oracle --import-server-name=<server> --import-instance="<myInstance>" --import-port-number=1521 --import-username=ERIKHO --import-password="<PW>" --import-accept-license --export siard-dk --export-folder=C:\AVID.SA.19782.1   

But in the following case when applying the filter it fails:
	java -jar "-Dfile.encoding=UTF-8" ../Programmer/dbptk-app-2.8.0.jar migrate -i oracle --import-server-name=<server> --import-instance="<myInstance>" --import-port-number=1521 --import-username=ERIKHO --import-password="<PW>" --import-accept-license --export siard-dk --export-folder=C:\AVID.SA.19782.1 --filter external-lobs --filter1-reference-type file-system --filter1-column-list C:\tabellerUdtraekTestSA.txt    
This is the error I get: 
	ERROR Unrecognized option: --filter1-reference-type

Even this command works but of course does nothing:
	java -jar "-Dfile.encoding=UTF-8" ../Programmer/dbptk-app-2.8.0.jar migrate -i oracle --import-server-name=<server> --import-instance="<myInstance>" --import-port-number=1521 --import-username=ERIKHO --import-password="<PW>" --import-accept-license --export siard-dk --export-folder=C:\AVID.SA.19782.1 --filter external-lobs 

It seems as if the filter no longer takes option parameters this way as the following help-command shows no options. Only output is:
	Filter module: -f external-lobs, --filter=external-lobs

So how do I specify what exact tables to export?

Brgds Erik Olesen

Attach the dbptk-app.log.txt file below.
Logfiles say only:
Database Preservation Toolkit (version 2.8.0) -- Conversion Report
==================================================================

- No issues to report.

**Comment by hmiguim** [comment]
Hi @ErikOlesen46, since version 2.7.0 DBPTK offers now a import-config module, see our wiki for more information about it (https://github.com/keeps/db-preservation-toolkit/wiki/Import-Config-Module). In a nutshell, the external LOB configuration is done inside this import-config file ([wiki](https://github.com/keeps/db-preservation-toolkit/wiki/Import-Config-Module#external-lobs)). 

Basically the changes are:

1. java -jar "-Dfile.encoding=UTF-8" ../Programmer/dbptk-app-2.8.0.jar migrate -i oracle --import-server-name= --import-instance="" --import-port-number=1521 --import-username=ERIKHO --import-password="" --import-accept-license --export import-config -ef /path/to/import-config.yaml

2. Edit the generated file as show in the wiki to select which column you want to configure as external LOB

3. java -jar "-Dfile.encoding=UTF-8" ../Programmer/dbptk-app-2.8.0.jar migrate -i import-config -if /path/o/import-config.yaml --export siard-dk --export-folder=C:\AVID.SA.19782.1 --filter external-lobs

Let me know if this helped you.

**Comment by ErikOlesen46** [comment]
Hi @hmiguim 

Spot on! Works perfectly. 

Thanks a lot!!

Brgds Erik Olesen

**Comment by hmiguim** [comment]
Nice! I'll close this issue.
